export function Assistant({ onAdd }) {
  const navigate = useNavigate()
  const location = useLocation()
  const contextProduct = location.state?.product
  const [messages, setMessages] = useState([{ role: 'agent', text: contextProduct ? `I can help you understand ${contextProduct.name}. What would you like to know?` : 'Hi! I can help you find products, compare options, check availability, manage your cart, and help with orders.' }])
  const [input, setInput] = useState('')
  const [busy, setBusy] = useState(false)
  const [sessionId, setSessionId] = useState('')
    const [orderPreview, setOrderPreview] = useState(null)
  const send = async (event) => {
    event.preventDefault()
    if (!input.trim() || busy) return
    const text = input.trim()
    setInput('')
    setMessages((items) => [...items, { role: 'user', text }])
    setBusy(true)
    try {
      const result = await sendAgentMessage(text, sessionId || undefined, undefined, contextProduct?._id)
      setSessionId(result.sessionId)
        setOrderPreview(result.orderPreview || null)
      setMessages((items) => [...items, { role: 'agent', text: result.message, products: result.products || [] }])
    } catch (error) {
      setMessages((items) => [...items, { role: 'agent', text: error.response?.data?.error?.message || 'Sorry, I could not connect to the shopping assistant right now.' }])
    } finally { setBusy(false) }
  }
    const placeOrder = async () => { setBusy(true); try { const order = await confirmAgentOrder(sessionId); setOrderPreview(null); setMessages((items) => [...items, { role: 'agent', text: `Your order ${order.id} has been placed successfully. Total: ${money(order.total)}. Status: ${order.status}.` }]) } catch (error) { setMessages((items) => [...items, { role: 'agent', text: error.response?.data?.error?.message || 'I could not place that order.' }]) } finally { setBusy(false) } }
    const cancelOrder = async () => { await cancelAgentOrder(sessionId); setOrderPreview(null); setMessages((items) => [...items, { role: 'agent', text: 'The order preview has been cancelled.' }]) }
    return <section className="agent-page"><div className="agent-header"><button className="back-link agent-back" onClick={() => navigate(-1)}><ArrowRight size={16} /> Back to Store</button><div><p className="eyebrow"><Bot size={14} /> AI shopping assistant</p><h1>Find your next favourite.</h1></div><span className="agent-status"><i /> Online / Ready</span></div><div className="agent-layout"><div className="agent-intro"><span className="assistant-avatar"><Bot size={28} /></span><p className="eyebrow">Personal shopping intelligence</p><h2>Ask. Discover.<br /><em>Buy better.</em></h2><p className="muted">Search the live catalogue, compare products, check stock, or manage your cart.</p>{contextProduct && <div className="agent-context"><small>Currently viewing</small><strong>{contextProduct.name}</strong><span>{money(contextProduct.price)}</span></div>}</div><div className="chat-window agent-chat"><div className="chat-messages">{messages.map((message, index) => <div className={`message ${message.role}`} key={`${index}-${message.text}`}><span>{message.role === 'agent' ? <Bot size={15} /> : 'You'}</span><p>{message.text}</p>{message.products?.length > 0 && <div className="chat-products">{message.products.map((product) => <article className="chat-product" key={product.id}><img src={imageFor(product)} alt={product.name} /><div><Link to={`/shop/products/${product.id}`}><strong>{product.name}</strong></Link><p>{money(product.price)}</p><button className="add-button" onClick={() => onAdd({ ...product, _id: product.id })}>Add to cart</button></div></article>)}</div>}</div>)}{orderPreview && <div className="order-preview"><strong>Order Summary</strong><span>{orderPreview.product.name} × {orderPreview.quantity}</span><span>Delivery: {orderPreview.profile.fullName}</span><span>{orderPreview.profile.address}, {orderPreview.profile.city}</span><b>Total: {money(orderPreview.total)}</b><button className="button primary" onClick={placeOrder} disabled={busy}>Place Order</button><button className="button outline" onClick={cancelOrder} disabled={busy}>Cancel</button></div>}{busy && <div className="message agent typing"><span><Bot size={15} /></span><p>Thinking<span className="typing-dots">...</span></p></div>}</div><div className="suggestions">{['Find a laptop under ₹70,000', 'Show me the best headphones', 'What can you help me with?'].map((suggestion) => <button key={suggestion} onClick={() => setInput(suggestion)}>{suggestion}</button>)}</div><form className="chat-form" onSubmit={send}><input value={input} onChange={(event) => setInput(event.target.value)} placeholder="Ask anything about products..." disabled={busy} /><button className="button primary" aria-label="Send" disabled={busy}><ArrowRight size={18} /></button></form></div></div></section>
}
import { useEffect, useMemo, useState } from 'react'
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom'
import { ArrowRight, Bot, Check, ChevronDown, Heart, Minus, Plus, Search, ShoppingBag, Sparkles, Star, Trash2, Truck, X } from 'lucide-react'
import { addToCart, getCart, getOrders, getProduct, getProducts, removeFromCart, sendAgentMessage, updateCartItem } from '../services/api'
import '../Agent.css'

const categories = ['Electronics', 'Fashion', 'Beauty', 'Home & Kitchen', 'Grocery', 'Sports', 'Books', 'Accessories']
const money = (value) => `₹${Number(value || 0).toLocaleString('en-IN')}`
const categoryImages = {
  phone: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80',
  laptop: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80',
  headphone: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80',
  watch: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80',
  tablet: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=900&q=80',
  camera: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80',
  monitor: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=80',
  keyboard: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80',
  gaming: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=900&q=80',
  sports: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=900&q=80',
  kitchen: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=900&q=80',
  accessory: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=900&q=80',
}
const imageFor = (product) => {
  if (product?.images?.[0]) return product.images[0]
  const text = `${product?.name || ''} ${product?.subcategory || ''} ${product?.category || ''}`.toLowerCase()
  const key = Object.keys(categoryImages).find((candidate) => text.includes(candidate)) || 'accessory'
  return categoryImages[key]
}
const imageErrorFallback = (event, product) => {
  const fallback = imageFor({ ...product, images: [] })
  if (event.currentTarget.src !== fallback) event.currentTarget.src = fallback
  else event.currentTarget.onerror = null
}

function ProductCard({ product, onAdd }) {
  const [busy, setBusy] = useState(false)
  const sellingPrice = product.price?.sellingPrice || product.price || 0
  const originalPrice = product.price?.mrp || product.originalPrice
  const discount = product.discountPercentage || product.price?.discountPercentage || (originalPrice ? Math.round((1 - sellingPrice / originalPrice) * 100) : 0)
  const handleAdd = async () => { setBusy(true); await onAdd(product); setBusy(false) }
  return <article className="product-card">
    <Link to={`/shop/products/${product._id}`} className="product-image-wrap"><img src={imageFor(product)} onError={(event) => imageErrorFallback(event, product)} alt={product.name} /><span className="ai-badge"><Sparkles size={13} /> AI pick</span><button className="icon-button wishlist" aria-label="Add to wishlist" onClick={(event) => event.preventDefault()}><Heart size={17} /></button></Link>
    <div className="product-card-body"><p className="eyebrow">{product.category}</p><Link to={`/shop/products/${product._id}`}><h3>{product.name}</h3></Link><div className="rating"><Star size={15} fill="currentColor" /> {product.ratings?.average || product.rating || '4.6'} <span>({product.ratings?.count || product.reviewCount || 0})</span></div><div className="price-row"><strong>{money(sellingPrice)}</strong>{originalPrice && <><del>{money(originalPrice)}</del><span className="discount">{discount}% off</span></>}</div><button className="add-button" onClick={handleAdd} disabled={busy || product.stock < 1}>{busy ? 'Adding...' : product.stock < 1 ? 'Out of stock' : 'Add to cart'}</button></div>
  </article>
}

export function ShopHome({ onAdd }) {
  const [products, setProducts] = useState([])
  const [state, setState] = useState('loading')
  useEffect(() => { getProducts({ limit: 8 }).then((data) => { setProducts(data.products); setState('ready') }).catch(() => setState('error')) }, [])
  return <div>
    <section className="hero"><div><p className="eyebrow light"><Sparkles size={15} /> Intelligence for every cart</p><h1>Shop smarter<br /><em>with AI.</em></h1><p className="hero-copy">Find things you will love, with recommendations that understand how you shop.</p><div className="hero-actions"><Link className="button primary" to="/shop/products">Explore products <ArrowRight size={17} /></Link><Link className="button ghost" to="/shop/ai-assistant"><Bot size={17} /> Ask the assistant</Link></div></div><div className="hero-orbit"><div className="orbit-ring ring-one" /><div className="orbit-ring ring-two" /><div className="robot-mark"><Bot size={76} strokeWidth={1.2} /></div><span className="floating-note note-one">Good match <Check size={14} /></span><span className="floating-note note-two"><Sparkles size={14} /> Personalised</span></div></section>
    <section className="section"><div className="section-heading"><div><p className="eyebrow">Browse by mood</p><h2>What are you looking for?</h2></div><Link to="/shop/products" className="text-link">View all <ArrowRight size={16} /></Link></div><div className="category-grid">{categories.map((category, index) => <Link key={category} to={`/shop/products?category=${encodeURIComponent(category)}`} className={`category-tile tile-${index % 4}`}><span>{['◈', '◌', '✦', '⌂', '◍', '△', '▤', '◇'][index]}</span><strong>{category}</strong><ArrowRight size={16} /></Link>)}</div></section>
    <section className="section featured"><div className="section-heading"><div><p className="eyebrow">Curated for you</p><h2>Recommended products</h2></div><Link to="/shop/products" className="text-link">See the collection <ArrowRight size={16} /></Link></div>{state === 'loading' && <div className="product-grid">{[1, 2, 3, 4].map((item) => <div className="skeleton" key={item} />)}</div>}{state === 'error' && <div className="notice error-state">Connect to the API to load your catalogue.</div>}{state === 'ready' && !products.length && <div className="notice">Your catalogue is empty. Add products in the merchant dashboard.</div>}{products.length > 0 && <div className="product-grid">{products.map((product) => <ProductCard key={product._id} product={product} onAdd={onAdd} />)}</div>}</section>
  </div>
}

export function Products({ onAdd }) {
  const queryCategory = new URLSearchParams(window.location.search).get('category') || ''
  const [filters, setFilters] = useState({ search: '', category: queryCategory, sort: 'relevance' })
  const [products, setProducts] = useState([])
  const [state, setState] = useState('loading')
  useEffect(() => { setState('loading'); getProducts({ search: filters.search || undefined, category: filters.category || undefined, limit: 50 }).then((data) => { setProducts(data.products); setState('ready') }).catch(() => setState('error')) }, [filters.search, filters.category])
  const shown = useMemo(() => [...products].sort((a, b) => filters.sort === 'low' ? a.price - b.price : filters.sort === 'high' ? b.price - a.price : filters.sort === 'rating' ? (b.rating || 0) - (a.rating || 0) : 0), [products, filters.sort])
  return <section className="section catalog"><div className="catalog-heading"><div><p className="eyebrow">The catalogue</p><h1>Find your next favourite.</h1><p className="muted">Search naturally, filter quickly, and let AI narrow it down.</p></div><Link className="ai-search" to="/shop/ai-assistant"><Bot size={17} /> Search with AI</Link></div><div className="catalog-toolbar"><label className="search-field"><Search size={18} /><input placeholder="Try ‘wireless headphones under 5000’" value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value })} /></label><select value={filters.category} onChange={(event) => setFilters({ ...filters, category: event.target.value })}><option value="">All categories</option>{categories.map((category) => <option key={category}>{category}</option>)}</select><select value={filters.sort} onChange={(event) => setFilters({ ...filters, sort: event.target.value })}><option value="relevance">Relevance</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option><option value="rating">Highest rated</option></select></div>{state === 'loading' && <div className="product-grid">{[1, 2, 3, 4, 5, 6].map((item) => <div className="skeleton" key={item} />)}</div>}{state === 'error' && <div className="notice error-state">We could not reach the catalogue. Check that the backend and MongoDB are running.</div>}{state === 'ready' && !shown.length && <div className="empty-state"><ShoppingBag size={32} /><h2>No products found</h2><p>Try another search or browse every category.</p><button className="button secondary" onClick={() => setFilters({ search: '', category: '', sort: 'relevance' })}>Clear filters</button></div>}{shown.length > 0 && <div className="product-grid">{shown.map((product) => <ProductCard key={product._id} product={product} onAdd={onAdd} />)}</div>}</section>
}

export function ProductDetails({ onAdd }) { const { id } = useParams(); const [product, setProduct] = useState(null); const [state, setState] = useState('loading'); const [quantity, setQuantity] = useState(1); useEffect(() => { getProduct(id).then((item) => { setProduct(item); setState('ready') }).catch(() => setState('error')) }, [id]); if (state === 'loading') return <div className="section"><div className="detail-loading" /></div>; if (state === 'error' || !product) return <div className="section empty-state"><X size={32} /><h2>Product unavailable</h2><Link className="button secondary" to="/shop/products">Back to products</Link></div>; return <section className="section product-detail"><Link className="back-link" to="/shop/products">← Back to products</Link><div className="detail-layout"><div className="detail-image"><img src={imageFor(product)} alt={product.name} /></div><div className="detail-copy"><p className="eyebrow">{product.category}</p><h1>{product.name}</h1><div className="rating large"><Star size={18} fill="currentColor" /> {product.rating || '4.6'} <span>{product.reviewCount || 0} reviews</span></div><div className="detail-price">{money(product.price)} <span>Inclusive of all taxes</span></div><p className="detail-description">{product.description || 'Thoughtfully selected for quality, value, and everyday performance.'}</p><div className="stock"><span /> {product.stock > 0 ? `${product.stock} available today` : 'Out of stock'}</div><div className="quantity"><button onClick={() => setQuantity(Math.max(1, quantity - 1))}><Minus size={16} /></button><strong>{quantity}</strong><button onClick={() => setQuantity(Math.min(product.stock, quantity + 1))}><Plus size={16} /></button></div><div className="detail-actions"><button className="button primary" disabled={!product.stock} onClick={() => onAdd(product, quantity)}>Add to cart</button><button className="button outline"><Heart size={17} /> Wishlist</button></div><div className="insight"><div className="insight-icon"><Sparkles size={18} /></div><div><strong>Why AI recommends this</strong><p>Highly rated by similar shoppers and a strong match for your recent browsing.</p></div></div></div></div></section> }

export function CartPage({ cart, setCart, onAdd }) { const navigate = useNavigate(); const [state, setState] = useState('loading'); useEffect(() => { getCart().then((value) => { setCart(value); setState('ready') }).catch(() => setState('error')) }, [setCart]); const items = cart?.items || []; const change = async (item, quantity) => { const value = await updateCartItem(item.productId._id, quantity, cart.merchantId); setCart(value) }; const remove = async (item) => setCart(await removeFromCart(item.productId._id, cart.merchantId)); if (state === 'loading') return <div className="section"><div className="detail-loading" /></div>; if (state === 'error') return <div className="section empty-state"><ShoppingBag size={32} /><h2>Your cart needs a connection</h2><p>Sign in and make sure the backend is running.</p></div>; return <section className="section cart-page"><div className="section-heading"><div><p className="eyebrow">Your selection</p><h1>Shopping cart</h1></div><span className="cart-count">{items.length} items</span></div>{!items.length ? <div className="empty-state"><ShoppingBag size={38} /><h2>Your cart is waiting for something amazing.</h2><Link className="button primary" to="/shop/products">Continue shopping</Link></div> : <div className="cart-layout"><div className="cart-items">{items.map((item) => <div className="cart-item" key={item.productId._id}><img src={imageFor(item.productId)} alt={item.productId.name} /><div className="cart-item-copy"><Link to={`/shop/products/${item.productId._id}`}><h3>{item.productId.name}</h3></Link><p>{item.productId.category}</p><strong>{money(item.price)}</strong><div className="quantity"><button onClick={() => item.quantity > 1 ? change(item, item.quantity - 1) : remove(item)}><Minus size={15} /></button><b>{item.quantity}</b><button onClick={() => change(item, item.quantity + 1)}><Plus size={15} /></button></div></div><button className="icon-button" onClick={() => remove(item)} aria-label="Remove product"><Trash2 size={17} /></button></div>)}<div className="cart-ai"><Sparkles size={21} /><div><strong>Smart savings</strong><p>Complete your setup with accessories selected by the AI assistant.</p></div><Link to="/shop/ai-assistant">Explore <ArrowRight size={15} /></Link></div></div><aside className="summary"><h2>Order summary</h2><div><span>Subtotal</span><strong>{money(cart.subtotal)}</strong></div><div><span>Delivery</span><strong className="free">FREE</strong></div><div><span>AI member saving</span><strong>-₹0</strong></div><hr /><div className="total"><span>Total</span><strong>{money(cart.total)}</strong></div><button className="button primary full" onClick={() => navigate('/shop/checkout')}>Proceed to checkout <ArrowRight size={16} /></button><p className="secure"><Truck size={15} /> Secure checkout · Razorpay ready</p></aside></div>}</section> }

export function LegacyAssistant({ onAdd }) { const [messages, setMessages] = useState([{ role: 'agent', text: 'Hi! I can help you find products, compare options, and build a better cart. What are you shopping for?' }]); const [input, setInput] = useState(''); const [busy, setBusy] = useState(false); const [sessionId, setSessionId] = useState(''); const send = async (event) => { event.preventDefault(); if (!input.trim() || busy) return; const text = input.trim(); setInput(''); setMessages((items) => [...items, { role: 'user', text }]); setBusy(true); try { const result = await sendAgentMessage(text, sessionId || undefined); setSessionId(result.sessionId); setMessages((items) => [...items, { role: 'agent', text: result.message, products: result.products || [] }]); } catch (error) { setMessages((items) => [...items, { role: 'agent', text: error.response?.data?.error?.message || 'I could not reach the shopping assistant. Please try again.' }]); } finally { setBusy(false); } }; return <section className="section assistant"><div className="assistant-intro"><span className="assistant-avatar"><Bot size={28} /></span><p className="eyebrow">Your shopping intelligence</p><h1>Ask, discover,<br /><em>buy better.</em></h1><p className="muted">Try “laptop for programming under ₹70,000” or “what goes well with my cart?”</p></div><div className="chat-window"><div className="chat-messages">{messages.map((message, index) => <div className={`message ${message.role}`} key={index}><span>{message.role === 'agent' ? <Bot size={15} /> : 'You'}</span><p>{message.text}</p>{message.products?.length > 0 && <div className="chat-products">{message.products.map((product) => <article className="chat-product" key={product.id}><img src={imageFor(product)} alt={product.name} /><div><Link to={`/shop/products/${product.id}`}><strong>{product.name}</strong></Link><p>{money(product.price)}</p><button className="add-button" onClick={() => onAdd({ ...product, _id: product.id })}>Add to cart</button></div></article>)}</div>}</div>)}</div>{busy && <div className="message agent"><span><Bot size={15} /></span><p>Searching the live catalogue...</p></div>}<div className="suggestions">{['Laptop under ₹70,000', 'Best headphones', 'Gift for my brother'].map((suggestion) => <button key={suggestion} onClick={() => setInput(suggestion)}>{suggestion}</button>)}</div><form className="chat-form" onSubmit={send}><input value={input} onChange={(event) => setInput(event.target.value)} placeholder="Ask anything about the catalogue..." disabled={busy} /><button className="button primary" aria-label="Send" disabled={busy}><ArrowRight size={18} /></button></form></div></section> }

export function Checkout({ cart }) { const [step, setStep] = useState(1); const [done, setDone] = useState(false); if (done) return <section className="section confirmation"><div className="success-mark"><Check size={30} /></div><p className="eyebrow">Order confirmed</p><h1>That’s a great choice.</h1><p>Your order <strong>#ACM{Math.floor(100000 + Math.random() * 900000)}</strong> is confirmed. We’ll keep you posted as it moves.</p><Link className="button primary" to="/shop/orders">Track order <ArrowRight size={16} /></Link></section>; return <section className="section checkout"><div className="checkout-steps">{['Address', 'Delivery', 'Payment'].map((label, index) => <button key={label} className={step === index + 1 ? 'active' : step > index + 1 ? 'complete' : ''} onClick={() => setStep(index + 1)}><span>{step > index + 1 ? <Check size={14} /> : index + 1}</span>{label}</button>)}</div><div className="checkout-panel"><p className="eyebrow">Step {step} of 3</p><h1>{step === 1 ? 'Where should we deliver?' : step === 2 ? 'Choose your delivery' : 'How would you like to pay?'}</h1>{step === 1 && <div className="form-grid"><input placeholder="Full name" /><input placeholder="Phone number" /><input className="wide" placeholder="Address" /><input placeholder="City" /><input placeholder="State" /><input placeholder="Pincode" /></div>}{step === 2 && <div className="delivery-options"><label><input type="radio" defaultChecked name="delivery" /> <span><strong>Standard delivery</strong><small>Arrives in 3–5 business days · Free</small></span></label><label><input type="radio" name="delivery" /> <span><strong>Express delivery</strong><small>Arrives tomorrow · ₹149</small></span></label></div>}{step === 3 && <div className="delivery-options"><label><input type="radio" defaultChecked name="payment" /> <span><strong>Razorpay</strong><small>UPI, cards and net banking</small></span></label><label><input type="radio" name="payment" /> <span><strong>Cash on delivery</strong><small>Pay when your order arrives</small></span></label></div>}<button className="button primary" onClick={() => step < 3 ? setStep(step + 1) : setDone(true)}>{step < 3 ? 'Continue' : `Pay ${money(cart?.total)}`} <ArrowRight size={16} /></button></div></section> }

export function OrderDashboard() {
  const [orders, setOrders] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    getOrders().then((data) => setOrders(data || [] )).catch(() => setOrders([])).finally(() => setLoading(false))
  }, [])

  if (loading) return <section className="section simple-page"><p className="eyebrow">Your journey</p><h1>Orders</h1><div className="empty-state"><Sparkles size={32} /><h2>Loading your orders…</h2></div></section>

  if (!orders.length) return <section className="section simple-page"><p className="eyebrow">Your journey</p><h1>Orders</h1><div className="empty-state"><Sparkles size={32} /><h2>No orders yet</h2><p>Your completed orders will appear here after checkout.</p></div></section>

  return <section className="section simple-page"><p className="eyebrow">Your journey</p><h1>Orders</h1><div className="cart-items" style={{ display: 'grid', gap: '16px' }}>{orders.map((order) => <div className="cart-item" key={order.id}><div className="cart-item-copy"><h3>Order #{order.id.slice(-6)}</h3><p>{order.product} × {order.quantity}</p><strong>{money(order.total)}</strong><p>Status: {order.status} · Payment: {order.paymentStatus}</p><p>Placed: {new Date(order.createdAt).toLocaleDateString('en-IN')}</p>{order.delivery && <p>Delivery: {order.delivery.address || `${order.delivery.city}, ${order.delivery.state}`}</p>}</div></div>)}</div></section>
}

export function SimplePage({ title, eyebrow, children }) { return <section className="section simple-page"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{children || <div className="empty-state"><Sparkles size={32} /><h2>Personal space, ready for your next order.</h2><p>Your saved items, order history, and preferences will appear here.</p></div>}</section> }
